config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'todos#index', as: :authenticated_root
  end

  root              to: 'static_pages#home'
  get    'about',   to: 'static_pages#about'
  get    'company', to: 'static_pages#company'

  resources :todos, only: [:index, :show, :edit, :update, :new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  validates :description, presence: true, allow_blank: true

  enum status: { active: 0, in_progress: 1, completed: 2 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render 'new'
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    render 'show' if @todo.update_attributes(todo_params)
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :status, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_footer.html.slim
footer#footer
  .footer-link
    ul
      li=link_to "About", about_path
      li=link_to "Company", company_path
  #copyright
    p Copyright © 2017 Syati.info

app/views/layouts/_header.html.slim
header#header
  .container.navigation
    = link_to 'MyTodos', root_path, class: 'm-navigation-title'
    ul.m-navigation-menu
      - if user_signed_in?
        li= link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        li= link_to 'log in', new_user_session_path
        li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? (t 'service.title', title: yield(:title)) : (t 'service.site_name')
    meta name="keywords"           content=(yield(:meta_keywords).presence || (t 'service.keywords'))
    meta name="description"        content=(yield(:meta_description).presence || (t 'service.description'))
    meta name="robots"             content="noodp"
    meta name="viewport"           content="width=device-width,initial-scale=1.0"
    meta property="og:title"       content=(content_for?(:title) ? (t 'service.title', title: yield(:title)) : (t 'service.site_name'))
    meta property="og:description" content=(yield(:meta_description).presence || (t 'service.description'))
    meta property="og:site_name"   content=t('service.site_name')
    meta property="og:image"       content=""
    meta property="og:type"        content="website"
    meta property="og:url"         content=""
    = csrf_meta_tags
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application', media: 'all'
  body
    main.wrapper
      == render "layouts/header"
      .container
        == yield
      == render "layouts/footer"

app/views/static_pages/about.html.slim
- provide :title, "About"
- provide :meta_description, "About Description"

h1 About

app/views/static_pages/company.html.slim
- provide :title, "Company"
- provide :meta_description, "Company Description"

h1 Company

app/views/static_pages/home.html.slim
- provide :title, "Home"
- provide :meta_description, "Home Description"

h1 Home

app/views/todos/edit.html.slim
= form_for @todo do |f|
  = f.text_field :title
  = f.select :status, Todo.statuses.keys.to_a
  = f.text_area :description
  = link_to t('.back'), todo_path(@todo), class: 'button button-outline'
  = f.submit t('.submit')

app/views/todos/index.html.slim
h1 Todos
= link_to t('.new'), new_todo_path
table
  thead
    tr
      th title
      th status
      th
  tbody
    - @todos.each do |todo|
      tr
        td
          = link_to todo.title, todo_path(todo)
        td = todo.status

app/views/todos/new.html.slim
= form_for @todo do |f|
  = f.text_field :title
  = f.select :status, Todo.statuses.keys.to_a
  = f.text_area :description
  = link_to t('.back'), todos_path, class: 'button button-outline'
  = f.submit t('.submit')

app/views/todos/show.html.slim
.todo-content
  .todo-content-title
    = @todo.title
  .todo-content-status
    = @todo.status
  .todo-content-description
    = @todo.description
= link_to t('.back'), todos_path, class: 'button button-outline'
= link_to t('.edit'), edit_todo_path(@todo), class: 'button'